name: Generate ASCII

on: push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v4

      - name: Install cowsay
        run: |
          chmod +x ascii.sh
          ./ascii.sh

