name: Generate ASCII

on: push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v4

      - name: Install cowsay
        run: |
          sudo apt-get update
          sudo apt-get install cowsay -y
          cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt
          grep -i "dragon" dragon.txt
          cat dragon.txt
          ls -ltrha