name: First ever action  # Unique name

on: push  # trigger

jobs:  # important part of the action
    first_job:   #name of the job
        runs-on: ubuntu-latest # github managed runner
        steps:
        - name: checkout repo
          uses: actions/checkout@v4   #this is pulled from marketplace to help authenticate with the repo and read all the info

        - name: List of commands to execute
          run: |
            echo "This is the first action"
            ls -ltrha
            cat README.md
            uptime
            hostname
            cat /etc/hosts